version: '3'

services:
  database:
    restart: always

  server:
    restart: always
    build:
      args:
        env: production
    networks:
      - default
      - proxy # only the container that interfaces with the proxy needs this
    environment:
      VIRTUAL_HOST: namegame.cwspear.ninja
      LETSENCRYPT_HOST: namegame.cwspear.ninja
      LETSENCRYPT_EMAIL: cameron@matchbooklab.com
      NODE_ENV: production

networks:
  default:
  proxy:
    external:
      name: pandora_proxy
