version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: namegame
      POSTGRES_PASSWORD: 02892gfh20-rikjfg2023ifri2

  server:
    build:
      context: .
    links:
      - database
