version: '3'

services:
  database:
    restart: unless-stopped

  server:
    restart: unless-stopped
    build:
      args:
        env: production
    networks:
      - default
      - proxy # only the container that interfaces with the proxy needs this
    environment:
      NODE_ENV: production
    labels:
      traefik.docker.network: pandora_proxy
      traefik.frontend.rule: Host:namegame.cwspear.ninja
      traefik.enable: true
      traefik.port: 7331
      traefik.http.middlewares.test-compress.compress: true

networks:
  default:
  proxy:
    external:
      name: pandora_proxy
